import type { Metadata } from "next";
import { Onest } from "next/font/google";
import { Bangers } from "next/font/google";
import { Paytone_One } from "next/font/google";
import { Work_Sans } from "next/font/google";
import { Oswald } from "next/font/google";

import { Header } from '@components/Header/Header'
import { Provider } from "@components/Provider";

import "@styles/globals.css";
import { Footer } from "@components/Footer";

const onest = Onest({ 
  subsets: ["latin"] ,
  variable: "--font-onest",
});

const workSans = Work_Sans({ 
  subsets: ["latin"],
  weight: ["700", "900"],
  variable: "--font-worksans",
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-surface">
      <body className={`${onest.variable} ${workSans.variable} wrapper`}>
        <div className="hero-bg"></div>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
